import SimpleBottomNavigation from "@/components/bottomNavigation/bottomNavigation";
import { BottomNavigation, Box } from "@mui/material";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "./header";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "فروشگاه",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
     <Box sx={{background:'#e1e1e1',margin:'auto',maxWidth:'478px',height:'100vh',overflow:"hidden",boxSizing: "border-box"}}>
      
      <Header/>
      

     {children}
     <SimpleBottomNavigation />
     </Box>
   
  );
}
